services:
    ledsproj:
        build: .
        restart: always
        image: ledsproj:latest
        env_file: .env
        networks:
            - internal
        depends_on:
            - db

    db:
        image: postgres:17.5-alpine
        restart: always
        shm_size: 128mb
        env_file: .env
        networks:
            - internal

    nginx:
        image: nginx:1.27.5-alpine
        restart: always
        ports:
            - 8080:8080
        networks:
            - default
            - internal
        depends_on:
            - ledsproj
        volumes:
            - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     networks:
    #         - default
    #         - internal

networks:
    default:
        driver: bridge
        enable_ipv6: false
    internal:
        name: internal
        driver: bridge
        internal: true
        enable_ipv6: false
